# -*- coding: utf-8 -*-
"""[osb]구명보트.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYxi9N7g1reb46GG8J1xO_e7uJvNfKRc
"""

def solution(people, limit):
    answer = 0
    people.sort() # 정렬 후
    first = 0
    last = len(people) -1

    while(first<=last):
        if(people[first]+people[last] <=limit):  # 두명 여부 확인
            first +=1
            last -=1
        else:   # 안될시 한명만 구하기
            last-=1
        answer +=1
    return answer