# -*- coding: utf-8 -*-
"""[OSB]프로세스.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MNqkpRrsJ26pZq8Nq_OalTX_DrCvW049
"""

from collections import deque
def solution(priorities, location):
    pri_len = len(priorities)
    pri = [i for i in range(1,pri_len+1)]
    pri = deque(pri)
    answer_val = pri[location] # 정답.
    sort_priorities = sorted(priorities, reverse=True) # 오름차순으로 정렬
    sort_priorities = deque(sort_priorities)
    order = []
    for v in priorities:
        temp = pri.popleft()
        if sort_priorities[0] == v: # 순서가 맞는 경우
            order.append(temp) # 순서에 추가
            sort_priorities.popleft()
        else:
            priorities.append(v)
            pri.append(temp)
    answer = order.index(answer_val)+1
    return answer