# -*- coding: utf-8 -*-
"""[OSB]이중우선순위큐.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_D7FzterR1yY4prVPUswkNWoOEwcQPj
"""

import heapq
def solution(operations):
    heap = []
    for value in operations:
        order, data = value.split() # 분리
        data = int(data)
        # 최대값 삭제
        if order == "D" and data == 1:
            if heap:
                max_value = max(heap)
                heap.remove(max_value)
        # 최소값 삭제
        elif order == "D" and data == -1:
            if heap:
                heapq.heappop(heap)
        # 데이터 넣기
        else:
            heapq.heappush(heap, data)

    if not heap:
        return [0, 0]

    answer = [max(heap), heap[0]]
    return answer