# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JxuYsKCnfhnM3DW6X-HhqHGLDH2nctMh
"""

from itertools import permutations as p

def solution(k, dungeons):
    answer = 0
    cntd = len(dungeons) ## count dungeons, ex) 5
    pod = p(range(cntd),cntd) ## path of dungeons, ex) (0,1,2,3,4)
    for i, path in enumerate(list(pod)):
        kk = k ## kk : 현재 피로도
        c = 0
        for j in path:
            if kk >= dungeons[j][0]:
                kk -= dungeons[j][1]
                c += 1
            else : break
        answer = max(answer,c)
    return answer