# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JxuYsKCnfhnM3DW6X-HhqHGLDH2nctMh
"""

def solution(sizes):
    w = []
    h = []
    for i, size in enumerate(sizes):
        w.append(max(size))
        h.append(min(size))
    answer = max(w) * max(h)
    return answer