# -*- coding: utf-8 -*-
"""[OSB]단속카메라.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SmLKJKkDcHDVsTRdgaFeNtJjWiffy2vQ
"""

def solution(routes):
    routes.sort(key = lambda x : x[1]) # 도착지 기준으로 정렬
    answer = 1
    first_end = routes[0][1]
    for start, end in routes :
        if start > first_end : # 안 만났을 경우.
            answer += 1
            first_end = end
    return answer