# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JxuYsKCnfhnM3DW6X-HhqHGLDH2nctMh
"""

def solution(word):
    answer = len(word)
    mul_mat = [781, 156, 31, 6, 1]
    checkword = [0 for x in range(len(word))]
    for i, n in enumerate(word):
        checkword[i] = "AEIOU".index(n)
    for j in range(len(word)):
        answer += mul_mat[j] * checkword[j]
    return answer