# -*- coding: utf-8 -*-
"""의상.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RvAzeUjCEFbjRvMiZlbo-a66qEoK1_iI
"""

def solution(clothes):
    cloth_dict = {}
    for i in clothes:
      if i[1] not in cloth_dict:
        cloth_dict[i[1]] = 1
      else:
        cloth_dict[i[1]] += 1
    print(cloth_dict)
    answer = 1
    # 경우를 안입을 경우 까지 고려해서 마지막에 -1
    for i in cloth_dict:
      answer *= (cloth_dict[i]+1)
    return answer-1
solution([["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]])
