# -*- coding: utf-8 -*-
"""[OSB]가장 큰 수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vd9CeQVLVUdQQFz2tmOcb6Qxz4Z6PvD8
"""

def solution(numbers):
    numbers = [str(num) for num in numbers] # 문자형으로 전환.
    numbers.sort(key=lambda x:x*4, reverse=True)
    answer = str(int(''.join(numbers))) # 0추가
    return answer