# -*- coding: utf-8 -*-
"""[OSB]K번째수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hLxy4I5BIM9a-kYxCPlMegp_26ayGZnz
"""

def solution(array, commands):
    answer = []
    for i, j, k in commands:
        temp = array[i-1:j]
        temp.sort()
        answer.append(temp[k-1])
    return answer