# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JxuYsKCnfhnM3DW6X-HhqHGLDH2nctMh
"""

from itertools import permutations as p

def is_prime(n):
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

def solution(numbers):
    answer = 0
    a = list(numbers)  ## a = ["1", "7"]
    b = []
    b += a
    if len(numbers) > 1:
        for i in range(1,len(a)):
            c = list(p(a, i+1))
            for j in c:
                b.append(''.join(j))
    ## b = ["1", "7", "17", "71"]
    num_list = list(set(list(map(int,b))))
    ## num_list = [1, 7, 17, 71]
    for j in num_list:
        j = int(j)
        if j <= 1:
            continue
        elif is_prime(j):
            answer += 1
    return answer