# -*- coding: utf-8 -*-
"""[OSB]주식가격.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z0CNFP46AF_cbKtrfupWoujoseBPSggb
"""

from collections import deque
def solution(prices):
    len_prices = len(prices)
    answer = []
    prices_dq = deque(prices)
    popnumber = 0 # 빠진 숫자
    for i in range(len_prices-1):
        temp = 0
        for index in range(i+1, len_prices):
            temp +=1
            if prices[i] > prices[index]:
                break
        answer.append(temp)
    answer.append(0)
    return answer
