# -*- coding: utf-8 -*-
"""[OSB]H-index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSKZXSQEto4HmrbAT69ItJ-7VB54XBjw
"""

def solution(citations):
    temp = 0
    citations.sort(reverse=True)
    for i, v in enumerate(citations):
        # 피인용수가 논문수보다 작아지기 시작하는 숫자가 바로 h.
        if i >= v:
            return i
    return len(citations) # 위에서 걸려지지 않는 경우